title: twenders
email: twendering@gmail.com
description: An archive of twenders.
baseurl: ""
url: "https://twenders.netlify.app"
github_username: twenders

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/

collections:
  bluebird:
    output: true
    permalink: /:path

plugins:
  - jekyll-feed
  - jekyll-postfiles
  - jekyll-seo-tag

exclude:
  - node_modules
  - dev-*
